name: telegraf
version: 1.5.2
summary: Telegraf agent
description: |
  Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics
confinement: classic
grade: stable
apps:
  telegraf:
    command: telegraf
    daemon: simple
parts:
  telegraf:
    source: .
    plugin: nil
    build: |
      export GOPATH=$(pwd)/go
      cd $GOPATH/src/github.com/influxdata/telegraf
      make
