name: telegraf
version: 1.5.3
summary: Telegraf agent
description: |
  Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics
confinement: classic
grade: stable
apps:
  telegraf:
    command: 'bin/telegraf.wrapper'
    daemon: simple
parts:
  telegraf:
    after: [snap-wrappers, go]
    # We should use the go plugin but we can't until snapcraft supports gdm
    # See https://bugs.launchpad.net/snapcraft/+bug/1748600
    plugin: nil
    build: |
      cd ..
      export GOPATH=$(pwd)/go
      export LDFLAGS=""
      mkdir -p $GOPATH
      go get -d github.com/influxdata/telegraf
      cd $GOPATH/src/github.com/influxdata/telegraf
      git checkout tags/1.5.3
      make
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp -p ../go/src/github.com/influxdata/telegraf/telegraf $SNAPCRAFT_PART_INSTALL/bin/telegraf
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      telegraf.snap_wrapper: bin/telegraf.wrapper
    stage:
      - bin/telegraf.wrapper
      - etc/telegraf.conf
  go:
    source-tag: go1.8
