name: telegraf
version: 1.5.2
summary: Telegraf agent
description: |
  Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics
confinement: classic
grade: stable
apps:
  telegraf:
    command: telegraf
    daemon: simple
parts:
  telegraf:
    source: https://github.com/influxdb/telegraf.git
    go-importpath: github.com/influxdb/telegraf
    plugin: go
